import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import { cn } from "@/lib/utils";
import SideNav from "@/components/SideNav";

import { Bell } from "lucide-react";
import { AvatarDemo } from "@/components/AvatarDemo";
import ThemeSwitch from "@/components/ThemeSwitch";
import ThemeLocalStore from "@/components/ThemeLocalStore";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Tasks App",
  description: "Generated by B.B.F",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-mode="light">
      <body
        className={cn(
          "min-h-screen font-sans antialiased grainy text-gray-950 dark:bg-gray-900/95 dark:text-gray-50 dark:text-opacity-90",
          fontSans.variable
        )}
      >
        <ThemeLocalStore />
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-72">
            <SideNav />
          </div>
          <MaxWidthWrapper className="flex-grow p-1 md:overflow-y-auto md:p-2">
            <div className="flex justify-end items-center mr-2 gap-x-6 mt-2">
              <ThemeSwitch />
              <Bell className="text-zinc-600 dark:text-white/50" />
              <div className="bg-zinc-700 rounded-full h-8 w-8">
                <AvatarDemo />
              </div>
            </div>
            {children}
          </MaxWidthWrapper>
        </div>
      </body>
    </html>
  );
}
